version: '3.8'

services:
  terraform-frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: terraform-frontend
      ports:
        - "3000:3000"
      depends_on:
        - terraform-server
      networks:
        - terraform-network
      restart: unless-stopped

  terraform-server:
    build: ./backend
    container_name: terraform-main-server
    ports:
      - "8000:5000"
    volumes:
      - ./backend/plugins:/app/plugins
      - ./backend/data:/app/data
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: python main.py
    restart: unless-stopped
    networks:
      - terraform-network

  error-aggregator:
    build: ./backend
    ports:
      - "50051:50051"
    volumes:
      - ./backend/plugins:/app/plugins
      - ./backend/data:/app/data
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    restart: unless-stopped
    networks:
      - terraform-network
    command: python plugins/error_aggregator.py

  security-scanner:
    build: ./backend
    ports:
      - "50052:50052"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend/plugins:/app/plugins
      - ./backend/data:/app/data
    working_dir: /app
    restart: unless-stopped
    networks:
      - terraform-network
    command: python plugins/security_scanner.py

  performance-analyzer:
    build: ./backend
    ports:
      - "50053:50053"
    volumes:
      - ./backend/plugins:/app/plugins
      - ./backend/data:/app/data
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    restart: unless-stopped
    networks:
      - terraform-network
    command: python plugins/performance_analyzer.py
      
networks:
  terraform-network:
    driver: bridge

volumes:
  app_data: